[project]
name = "erc721-tool"
authors = ["ERC721 Tool Team"]
description = "A comprehensive NFT management toolkit for Stacks blockchain"
telemetry = false
requirements = []

[contracts.nft-registry]
path = "contracts/nft-registry.clar"
depends_on = []

[contracts.nft-access]
path = "contracts/nft-access.clar"
depends_on = ["nft-registry"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
